services:
  delivery:
    container_name: delivery-service
    image: delivery-service
    build: ./delivery-status-service
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/tracking_delivery_db
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - KAFKA_URL=kafka:9092
    depends_on:
      - db
      - kafka

  tracking:
    container_name: tracking-service
    image: tracking-service
    build: ./tracking-service
    restart: always
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/tracking_delivery_db
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - KAFKA_URL=kafka:9092
    depends_on:
      - db
      - kafka

  notification:
    container_name: notification-service
    image: notification-service
    build: ./notification-service
    restart: always
    environment:
      - KAFKA_URL=kafka:9092
    depends_on:
      - kafka

  db:
    image: postgres
    container_name: postgresql
    hostname: db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: tracking_delivery_db
    ports:
      - 5433:5432

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka_broker
    hostname: kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
